function results = myimfcn(varargin)
% Image Processing Function
% VARARGIN - Can contain up to two inputs: 
%   IM - First input is a numeric array containing the image data. 
%   INFO - Second input is a scalar structure containing information about 
%          the input image source.
%   RESULTS - A scalar struct with the processing results.

%----------------------
% Auto-generated by imageBatchProcessor App. 
% When used by the App, this function will be called 
% for each input image file automatically.
%----------------------

% Input parsing
im = varargin{1};
if nargin == 2
    % Obtain information about the input image source
    info = varargin{2};
end
%----------------------
% Replace the sample below with your code
imgray = im2gray(im);
bw = imbinarize(imgray);
results.imgray = imgray;
results.bw     = bw;
%----------------------